### ISSUE TITLE
Crashes with feather client

### ISSUE THREAD

**Issue by OmegaPhoenix637** [kennytv/kennytvs-epic-force-close-loading-screen-mod-for-fabric#22]
Crashes with feather client

info: [2023-07-27T12:04:08Z DEBUG rust_launcher::downloader] Downloading https://game-launcher.feathermc.com/release/version_index.json to C:\Users\AppData\Roaming\.minecraft\version_index.json...
info: [2023-07-27T12:04:08Z DEBUG rust_launcher::downloader] Download from https://game-launcher.feathermc.com/release/version_index.json to C:\Users\AppData\Roaming\.minecraft\version_index.json completed.
info: CONNECTING TO SERVER undefined
info: [2023-07-27T12:04:08Z INFO  rust_launcher::start::bindings] server: None
info: [2023-07-27T12:04:09Z INFO  rust_launcher::start] Loading version
info: {"versionSize":220266179,"state":{"VersionLoading":true},"currentDownloadRate":0,"expectedTasks":6,"downloadSpeed":0,"downloaded":0}
info: [2023-07-27T12:04:09Z INFO  rust_launcher::start] Finished loading version
info: [2023-07-27T12:04:09Z INFO  rust_launcher::start] Finished moving mods
info: {"versionSize":220266179,"state":{"Downloading":["Mods","Jre","Libraries","Assets"]},"currentDownloadRate":0,"expectedTasks":6,"downloadSpeed":0,"downloaded":79646}
info: [2023-07-27T12:04:09Z INFO  rust_launcher::start] Preparing assets
[2023-07-27T12:04:09Z INFO  rust_launcher::start] Preparing JRE
info: [2023-07-27T12:04:09Z DEBUG rust_launcher::start] Finished preparing JRE
[2023-07-27T12:04:09Z INFO  rust_launcher::start] Preparing libraries
info: {"versionSize":220266179,"state":{"Downloading":["Mods","Libraries","Assets"]},"currentDownloadRate":0,"expectedTasks":6,"downloadSpeed":0,"downloaded":43227527}
info: [2023-07-27T12:04:09Z INFO  rust_launcher::start] Preparing mods
info: [2023-07-27T12:04:09Z INFO  rust_launcher::start] Finished preparing mods
info: {"versionSize":220266179,"state":{"Downloading":["Libraries","Assets"]},"currentDownloadRate":0,"expectedTasks":6,"downloadSpeed":0,"downloaded":57085304}
info: [2023-07-27T12:04:09Z INFO  rust_launcher::start] Finished preparing assets
info: {"versionSize":220266179,"state":{"Downloading":["Libraries"]},"currentDownloadRate":0,"expectedTasks":6,"downloadSpeed":0,"downloaded":714577262}
info: [2023-07-27T12:04:09Z INFO  rust_launcher::start] Finished preparing libraries
[2023-07-27T12:04:09Z INFO  rust_launcher::start] Preparing registry
info: {"versionSize":220266179,"state":{"Jvm":true},"currentDownloadRate":0,"expectedTasks":6,"downloadSpeed":0,"downloaded":808593632}
info: [2023-07-27T12:04:09Z INFO  rust_launcher::start] Finished preparing registry
info: [2023-07-27T12:04:09Z INFO  rust_launcher::common::launch] starting JVM with arguments: ["-Djava.library.path=libraries/native\\net/digitalingot/fcef-windows/0.0.5\\extracted/;libraries/native\\net/digitalingot/fwebp-windows/0.0.1\\extracted/;libraries/native\\net/digitalingot/favif-windows/0.0.1\\extracted/;libraries/native\\de/jcm/discord-game-sdk4j-windows/0.5.4\\extracted/;libraries/native\\org/jitsi/jnopus/1.0\\extracted/;libraries/native\\org/lwjgl/lwjgl/3.3.1\\extracted/;libraries/native\\org/lwjgl/lwjgl-jemalloc/3.3.1\\extracted/;libraries/native\\org/lwjgl/lwjgl-openal/3.3.1\\extracted/;libraries/native\\org/lwjgl/lwjgl-opengl/3.3.1\\extracted/;libraries/native\\org/lwjgl/lwjgl-glfw/3.3.1\\extracted/;libraries/native\\org/lwjgl/lwjgl-stb/3.3.1\\extracted/;libraries/native\\org/lwjgl/lwjgl-tinyfd/3.3.1\\extracted/;libraries/native\\com/mojang/text2speech/1.13.9\\extracted/", "--add-opens=java.desktop/java.awt.event=ALL-UNNAMED", "--add-opens=java.desktop/java.awt.color=ALL-UNNAMED", "--add-opens=java.desktop/java.awt=ALL-UNNAMED", "--add-opens=java.base/java.lang=ALL-UNNAMED", "-Xmx6077M", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseG1GC", "-XX:G1NewSizePercent=20", "-XX:G1ReservePercent=20", "-XX:MaxGCPauseMillis=50", "-XX:G1HeapRegionSize=32M", "-Dlog4j2.formatMsgNoLookups=true", "-XX:ErrorFile=feather/java_error.log", "-Djavax.accessibility.assistive_technologies=", "-Djavax.net.ssl.trustStoreType=WINDOWS-ROOT", "-Xms6G", "-Xmx6G", "-Xmn768m", "-XX:+AlwaysPreTouch", "-XX:+DisableExplicitGC", "-XX:+ParallelRefProcEnabled", "-XX:+PerfDisableSharedMem", "-XX:+UseCompressedOops", "-XX:-UsePerfData", "-XX:MaxGCPauseMillis=200", "-XX:ParallelGCThreads=8", "-XX:ConcGCThreads=2", "-XX:+UseG1GC", "-XX:InitiatingHeapOccupancyPercent=50", "-XX:G1HeapRegionSize=1", "-XX:G1HeapWastePercent=5", "-XX:G1MixedGCCountTarget=8", "-cp", "libraries\\java\\net/minecraft/client/1.19.4/minecraft-1.19.4.jar;libraries\\java\\net/fabricmc/tiny-mappings-parser/0.3.0+build.17/tiny-mappings-parser-0.3.0+build.17.jar;libraries\\java\\net/fabricmc/sponge-mixin/0.12.4+mixin.0.8.5/sponge-mixin-0.12.4+mixin.0.8.5.jar;libraries\\java\\net/fabricmc/tiny-remapper/0.8.2/tiny-remapper-0.8.2.jar;libraries\\java\\net/fabricmc/access-widener/2.1.0/access-widener-2.1.0.jar;libraries\\java\\org/ow2/asm/asm/9.4/asm-9.4.jar;libraries\\java\\org/ow2/asm/asm-analysis/9.4/asm-analysis-9.4.jar;libraries\\java\\org/ow2/asm/asm-commons/9.4/asm-commons-9.4.jar;libraries\\java\\org/ow2/asm/asm-tree/9.4/asm-tree-9.4.jar;libraries\\java\\org/ow2/asm/asm-util/9.4/asm-util-9.4.jar;libraries\\java\\net/fabricmc/intermediary/1.19.4/intermediary-1.19.4.jar;libraries/java\\net/fabricmc/fabric-loader/0.14.21/fabric-loader-0.14.21.jar;libraries\\java\\de/javagl/obj/0.3.0/obj-0.3.0.jar;libraries\\java\\de/jcm/discord-game-sdk4j/0.5.4/discord-game-sdk4j-0.5.4;libraries\\java\\net/digitalingot/feather-server-api-proto/1.1-SNAPSHOT/feather-server-api-proto-1.1-SNAPSHOT.jar;libraries\\java\\software/bernie/geckolib/geckolib-fabric-1.19-3.3.0.jar;libraries\\java\\net/digitalingot/rust-extension/1.0.7/rust-extension-1.0.7.jar;libraries\\java\\net/digitalingot/fcef/0.0.5/fcef-0.0.5.jar;libraries\\java\\net/digitalingot/fwebp/0.0.1/fwebp-0.0.1.jar;libraries\\java\\net/digitalingot/favif/0.0.1/favif-0.0.1.jar;libraries\\java\\net/digitalingot/feather-server-api/messaging/0.0.2/messaging-0.0.2-SNAPSHOT.jar;libraries\\java\\net/digitalingot/feather-server-api/api/0.0.2/api-0.0.2-SNAPSHOT.jar;libraries\\java\\org/jitsi/libjitsi/1.0-CUSTOM/libjitsi-1.0-CUSTOM.jar;libraries\\java\\org/jitsi/jitsi-utils/1.0-45-gc3afb76/jitsi-utils-1.0-45-gc3afb76.jar;libraries\\java\\org/capnproto/runtime/0.1.10/runtime-0.1.10.jar;libraries\\java\\com/google/inject/guice/5.1.0/guice-vendored-5.1.0.jar;libraries\\java\\javassist/javassist/3.12.1.GA/javassist-3.12.1.GA.jar;libraries\\java\\com/github/oshi/oshi-core/6.2.2/oshi-core-6.2.2.jar;libraries\\java\\com/google/code/gson/gson/2.10/gson-2.10.jar;libraries\\java\\com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar;libraries\\java\\com/google/guava/guava/31.1-jre/guava-31.1-jre.jar;libraries\\java\\com/ibm/icu/icu4j/71.1/icu4j-71.1.jar;libraries\\java\\com/mojang/authlib/3.18.38/authlib-3.18.38.jar;libraries\\java\\com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar;libraries\\java\\com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar;libraries\\java\\com/mojang/datafixerupper/6.0.6/datafixerupper-6.0.6.jar;libraries\\java\\com/mojang/javabridge/2.0.25/javabridge-2.0.25.jar;libraries\\java\\com/mojang/logging/1.1.1/logging-1.1.1.jar;libraries\\java\\com/mojang/patchy/2.2.10/patchy-2.2.10.jar;libraries\\java\\com/mojang/text2speech/1.13.9/text2speech-1.13.9.jar;libraries\\java\\commons-codec/commons-codec/1.15/commons-codec-1.15.jar;libraries\\java\\commons-io/commons-io/2.11.0/commons-io-2.11.0.jar;libraries\\java\\commons-logging/commons-logging/1.2/commons-logging-1.2.jar;libraries\\java\\io/netty/netty-codec-http/4.1.82.Final/netty-codec-http-4.1.82.Final.jar;libraries\\java\\io/netty/netty-buffer/4.1.82.Final/netty-buffer-4.1.82.Final.jar;libraries\\java\\io/netty/netty-codec/4.1.82.Final/netty-codec-4.1.82.Final.jar;libraries\\java\\io/netty/netty-common/4.1.82.Final/netty-common-4.1.82.Final.jar;libraries\\java\\io/netty/netty-handler/4.1.82.Final/netty-handler-4.1.82.Final.jar;libraries\\java\\io/netty/netty-resolver/4.1.82.Final/netty-resolver-4.1.82.Final.jar;libraries\\java\\io/netty/netty-transport-classes-epoll/4.1.82.Final/netty-transport-classes-epoll-4.1.82.Final.jar;libraries\\java\\io/netty/netty-transport-native-unix-common/4.1.82.Final/netty-transport-native-unix-common-4.1.82.Final.jar;libraries\\java\\io/netty/netty-transport/4.1.82.Final/netty-transport-4.1.82.Final.jar;libraries\\java\\it/unimi/dsi/fastutil/8.5.9/fastutil-8.5.9.jar;libraries\\java\\net/java/dev/jna/jna-platform/5.12.1/jna-platform-5.12.1.jar;libraries\\java\\net/java/dev/jna/jna/5.12.1/jna-5.12.1.jar;libraries\\java\\net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar;libraries\\java\\org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar;libraries\\java\\org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar;libraries\\java\\org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar;libraries\\java\\org/apache/httpcomponents/httpcore/4.4.15/httpcore-4.4.15.jar;libraries\\java\\org/apache/logging/log4j/log4j-api/2.19.0/log4j-api-2.19.0.jar;libraries\\java\\org/apache/logging/log4j/log4j-core/2.19.0/log4j-core-2.19.0.jar;libraries\\java\\org/apache/logging/log4j/log4j-slf4j2-impl/2.19.0/log4j-slf4j2-impl-2.19.0.jar;libraries\\java\\org/joml/joml/1.10.5/joml-1.10.5.jar;libraries\\java\\org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1.jar;libraries\\java\\org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1.jar;libraries\\java\\org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1.jar;libraries\\java\\org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1.jar;libraries\\java\\org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1.jar;libraries\\java\\org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1.jar;libraries\\java\\org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1.jar;libraries\\java\\org/slf4j/slf4j-api/2.0.1/slf4j-api-2.0.1.jar", "net.digitalingot.rustextension.ProxiedStart", "net.fabricmc.loader.launch.knot.KnotClient", "--username", "Fe4thers", "--version", "1.19.4-feather", "--gameDir", "C:\\Users\\AppData\\Roaming/.minecraft", "--assetsDir", "assets", "--assetIndex", "1.19.4-feather-game", "--uuid", "f892a86254a54f05873d88ceb5a4d494", "--accessToken", "<hidden>", "--userType", "msa", "--versionType", "feather"]
info: sending javaw pid
info: starting cleanup
info: [14:04:11] [main/INFO]: Loading Minecraft 1.19.4 with Fabric Loader 0.14.21
info: [14:04:11] [main/INFO]: Loading 56 mods:
	- fabric-api 0.85.0+1.19.4
	   |-- fabric-api-base 0.4.27+1e9487d2f4
	   |-- fabric-api-lookup-api-v1 1.6.28+504944c8f4
	   |-- fabric-biome-api-v1 13.0.9+10ce000ff4
	   |-- fabric-block-api-v1 1.0.8+e022e5d1f4
	   |-- fabric-blockrenderlayer-v1 1.1.37+10ce000ff4
	   |-- fabric-client-tags-api-v1 1.1.0+0eee1254f4
	   |-- fabric-command-api-v1 1.2.30+f71b366ff4
	   |-- fabric-command-api-v2 2.2.9+10ce000ff4
	   |-- fabric-commands-v0 0.2.47+df3654b3f4
	   |-- fabric-containers-v0 0.1.57+df3654b3f4
	   |-- fabric-content-registries-v0 3.5.13+10ce000ff4
	   |-- fabric-convention-tags-v1 1.5.2+10ce000ff4
	   |-- fabric-crash-report-info-v1 0.2.17+aeb40ebef4
	   |-- fabric-data-generation-api-v1 11.4.4+10ce000ff4
	   |-- fabric-dimensions-v1 2.1.48+10ce000ff4
	   |-- fabric-entity-events-v1 1.5.16+10ce000ff4
	   |-- fabric-events-interaction-v0 0.6.0+10ce000ff4
	   |-- fabric-events-lifecycle-v0 0.2.55+df3654b3f4
	   |-- fabric-game-rule-api-v1 1.0.35+a1ccd7bff4
	   |-- fabric-item-api-v1 2.1.20+10ce000ff4
	   |-- fabric-item-group-api-v1 3.0.9+da41e1a9f4
	   |-- fabric-key-binding-api-v1 1.0.35+504944c8f4
	   |-- fabric-keybindings-v0 0.2.33+df3654b3f4
	   |-- fabric-lifecycle-events-v1 2.2.18+10ce000ff4
	   |-- fabric-loot-api-v2 1.1.31+10ce000ff4
	   |-- fabric-loot-tables-v1 1.1.35+9e7660c6f4
	   |-- fabric-message-api-v1 5.1.4+10ce000ff4
	   |-- fabric-mining-level-api-v1 2.1.43+10ce000ff4
	   |-- fabric-models-v0 0.3.33+10ce000ff4
	   |-- fabric-networking-api-v1 1.3.4+10ce000ff4
	   |-- fabric-networking-v0 0.3.44+df3654b3f4
	   |-- fabric-object-builder-api-v1 7.1.0+d63b52eaf4
	   |-- fabric-particles-v1 1.1.0+86d48884f4
	   |-- fabric-recipe-api-v1 1.0.11+10ce000ff4
	   |-- fabric-registry-sync-v0 2.2.3+10ce000ff4
	   |-- fabric-renderer-api-v1 2.4.0+c6bbc80df4
	   |-- fabric-renderer-indigo 1.4.0+c6bbc80df4
	   |-- fabric-renderer-registries-v1 3.2.41+df3654b3f4
	   |-- fabric-rendering-data-attachment-v1 0.3.31+10ce000ff4
	   |-- fabric-rendering-fluids-v1 3.0.24+10ce000ff4
	   |-- fabric-rendering-v0 1.1.44+df3654b3f4
	   |-- fabric-rendering-v1 2.1.4+10ce000ff4
	   |-- fabric-resource-conditions-api-v1 2.3.3+10ce000ff4
	   |-- fabric-resource-loader-v0 0.11.6+d3afe6c3f4
	   |-- fabric-screen-api-v1 1.0.48+10ce000ff4
	   |-- fabric-screen-handler-api-v1 1.3.23+10ce000ff4
	   |-- fabric-sound-api-v1 1.0.11+10ce000ff4
	   |-- fabric-transfer-api-v1 3.2.2+c956c0e6f4
	   \-- fabric-transitive-access-wideners-v1 3.2.0+10ce000ff4
	- fabricloader 0.14.21
	- feather 1.0.0-SNAPSHOT
	- forcecloseworldloadingscreen 2.1.0
	- java 17
	- minecraft 1.19.4
	- modmenu 6.2.1
info: [14:04:11] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users
/AppData/Roaming/.minecraft/libraries/java/net/fabricmc/sponge-mixin/0.12.4+mixin.0.8.5/sponge-mixin-0.12.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
info: [14:04:12] [main/INFO]: Compatibility level set to JAVA_16
info: [14:04:12] [main/INFO]: Compatibility level set to JAVA_17
info: [14:04:12] [main/INFO]: [Feather::EssentialMod] Installed: false
info: [14:04:12] [main/WARN]: Error loading class: net/optifine/Config (java.lang.ClassNotFoundException: net/optifine/Config)
info: [14:04:19] [Render thread/WARN]: @Redirect conflict. Skipping forcecloseloadingscreen.mixins.json:MinecraftMixin from mod forcecloseworldloadingscreen->@Redirect::updateScreenAndTick(Lnet/minecraft/class_310;Lnet/minecraft/class_437;)V with priority 1000, already redirected by mixins.feather.json:sn from mod feather->@Redirect::ld(Lnet/minecraft/class_310;Lnet/minecraft/class_437;)V with priority 1000
info: [14:04:19] [Render thread/WARN]: @Redirect conflict. Skipping forcecloseloadingscreen.mixins.json:MinecraftMixin from mod forcecloseworldloadingscreen->@Redirect::updateScreenAndTick(Lnet/minecraft/class_310;Lnet/minecraft/class_437;)V with priority 1000, already redirected by mixins.feather.json:sn from mod feather->@Redirect::ld(Lnet/minecraft/class_310;Lnet/minecraft/class_437;)V with priority 1000
info: [14:04:19] [Render thread/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_310 failed
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) ~[fabric-loader-0.14.21.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.digitalingot.rustextension.ProxiedStart.main(ProxiedStart.java:16) ~[rust-extension-1.0.7.jar:?]
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_310 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:207) ~[minecraft-1.19.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	... 7 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:207) ~[minecraft-1.19.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	... 7 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector updateScreenAndTick(Lnet/minecraft/class_310;Lnet/minecraft/class_437;)V in forcecloseloadingscreen.mixins.json:MinecraftMixin from mod forcecloseworldloadingscreen failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap forcecloseloadingscreen-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:207) ~[minecraft-1.19.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	... 7 more
info: [2023-07-27T12:04:20Z INFO  rust_launcher::start::bindings] launch stalled

**Comment by stepanpanik** [comment]
i have this problem too.

**Comment by AnOpenSauceDev** [comment]
#21
